# Generated by Django 2.2.5 on 2020-12-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rub',
        ),
    ]
