# Generated by Django 2.2.6 on 2020-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200626_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='阅读量'),
        ),
    ]
