# Generated by Django 2.2.5 on 2020-12-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=5)),
                ('no', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('no', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('question', mdeditor.fields.MDTextField()),
                ('answer', mdeditor.fields.MDTextField()),
                ('difficulty', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('accepted', models.IntegerField(blank=True, default=0, null=True)),
                ('attempted', models.IntegerField(blank=True, default=0, null=True)),
                ('pass_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('tag', models.ManyToManyField(to='luogu.Tag')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('body', mdeditor.fields.MDTextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myUser',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='luogu.Question')),
            ],
            options={
                'db_table': 'History',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=32, verbose_name='用户名称')),
                ('telephone', models.CharField(default='', max_length=20, verbose_name='联系方式')),
                ('consumption_amount', models.IntegerField(default=0, verbose_name='消费金额')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('types', models.CharField(default='', max_length=20, verbose_name='类型')),
                ('contact_person', models.CharField(default='', max_length=32, verbose_name='联系人')),
                ('total_shopping_cart', models.IntegerField(default=0, verbose_name='购物车金额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
