# Generated by Django 2.2.5 on 2020-12-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('luogu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('name', models.CharField(default='', max_length=256, verbose_name='商品名称')),
                ('purchase_price', models.FloatField(default=0, verbose_name='进货价')),
                ('selling_price', models.FloatField(default=0, verbose_name='售价')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('origin_address', models.CharField(default='', max_length=256, verbose_name='产地')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('shelf_life', models.DateField(verbose_name='保质期')),
                ('standard', models.IntegerField(default=0, verbose_name='规格')),
                ('detail', models.CharField(default='', max_length=256, verbose_name='商品详情')),
                ('img', models.ImageField(blank=True, null=True, upload_to='luogu/commodity_img/', verbose_name='商品图片')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0, verbose_name='总金额')),
                ('order_creation_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('payment_method', models.CharField(default='', max_length=32, verbose_name='支付方式')),
                ('name', models.CharField(default='', max_length=32, verbose_name='收货人')),
                ('telephone', models.CharField(default='', max_length=32, verbose_name='联系方式')),
                ('area', models.CharField(default='', max_length=256, verbose_name='省市区街道')),
                ('address', models.CharField(default='', max_length=256, verbose_name='详细地址')),
                ('address_tag', models.CharField(default='', max_length=256, verbose_name='地址标签')),
                ('real_payment', models.FloatField(default=0, verbose_name='实付款')),
                ('shipping', models.FloatField(default=0, verbose_name='运费')),
                ('discounted_price', models.FloatField(default=0, verbose_name='优惠金额')),
                ('deposit', models.FloatField(default=0, verbose_name='定金')),
                ('payment_status', models.BooleanField(default=False, verbose_name='支付状态')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.IntegerField(verbose_name='商品id')),
                ('unit_price', models.FloatField(default=0, verbose_name='商品单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='商品数量')),
                ('order', models.ForeignKey(on_delete='订单', to='luogu.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('sales_amount', models.IntegerField(default=0, verbose_name='销售额')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='收货人')),
                ('telephone', models.CharField(default='', max_length=32, verbose_name='联系方式')),
                ('area', models.CharField(default='', max_length=256, verbose_name='省市区街道')),
                ('address', models.CharField(default='', max_length=256, verbose_name='详细地址')),
                ('address_tag', models.CharField(default='', max_length=256, verbose_name='地址标签')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0, verbose_name='商品单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='商品数量')),
                ('commodity', models.ForeignKey(on_delete='Commodity', to='luogu.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=32, verbose_name='员工名称')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('gender', models.CharField(default='unknown', max_length=20, verbose_name='性别')),
                ('address', models.CharField(max_length=255, verbose_name='家庭地址')),
                ('position', models.CharField(default='Employee', max_length=20, verbose_name='职位')),
                ('salary', models.IntegerField(default=0, verbose_name='薪资')),
                ('entry_date', models.DateField(verbose_name='入职日期')),
                ('resignation_date', models.DateField(blank=True, verbose_name='离职日期')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contributions',
        ),
        migrations.RemoveField(
            model_name='history',
            name='question',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_level',
            field=models.IntegerField(default=0, verbose_name='客户等级'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consumption_amount',
            field=models.FloatField(default=0, verbose_name='消费金额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(default='', max_length=32, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_shopping_cart',
            field=models.FloatField(default=0, verbose_name='购物车金额'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='shopping_cart_details',
            name='customer',
            field=models.ForeignKey(on_delete='Customer', to='luogu.Customer'),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='customer',
            field=models.ForeignKey(on_delete='Customer', to='luogu.Customer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete='员工', to='luogu.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete='客户', to='luogu.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete='员工', to='luogu.Staff'),
        ),
    ]
