# Generated by Django 2.2.5 on 2020-12-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0003_auto_20201228_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': '商品管理', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工管理', 'verbose_name_plural': '员工管理'},
        ),
    ]
