# Generated by Django 2.2.5 on 2020-12-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0005_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AlterModelOptions(
            name='order_detail',
            options={'verbose_name': '订单明细', 'verbose_name_plural': '订单明细'},
        ),
    ]
