# Generated by Django 2.2.5 on 2020-12-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0006_auto_20201230_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order_detail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
