# Generated by Django 2.2.5 on 2020-12-31 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0008_auto_20201231_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Staff'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Order'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Staff'),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Customer'),
        ),
        migrations.AlterField(
            model_name='shopping_cart_details',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luogu.Customer'),
        ),
    ]
