# Generated by Django 2.2.5 on 2021-01-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0009_auto_20201231_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='commodity_id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='luogu.Commodity'),
            preserve_default=False,
        ),
    ]
