# Generated by Django 2.2.5 on 2021-01-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0010_auto_20210105_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='commodity',
        ),
    ]
