# Generated by Django 2.2.5 on 2021-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0011_remove_order_detail_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='commodity_id',
            field=models.IntegerField(default=0, verbose_name='商品ID'),
        ),
    ]
