# Generated by Django 2.2.5 on 2021-01-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0012_order_detail_commodity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='commodity_id',
        ),
    ]
