# Generated by Django 2.2.5 on 2021-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0013_remove_order_detail_commodity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='commodity_id',
            field=models.IntegerField(default=0, verbose_name='商品ID'),
        ),
    ]
