# Generated by Django 2.2.5 on 2021-01-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0015_auto_20210105_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='商品单价'),
        ),
    ]
